### ISSUE TITLE
Nuke the `svm-common` crate

### ISSUE THREAD

**Issue by YaronWittenstein** [spacemeshos/svm#267]
The current `svm-common` crate has almost nothing left inside.
All the functionality it originally had, has incrementally moved into different places (mainly to the `svm-types` crate).

The remaining code could be probably moved to a different target.
Another alternative is to rename the crate to a have more meaningful name. (the term `common` doesn't tell much)

**Comment by neysofu** [comment]
I've thought about this and I actually like the idea of a `svm-common` crate where, rather than removing stuff, we can dump small utility functions that might get called from multiple crates. At the moment, we only have `fmt_hex`, which I personally would replace with a real serialization format like Base16, which of course doesn't have commas but has the benefit of being a standard.

What we can do:

- Keep the `svm-common` crate (as in "common utilities").
- Rename `svm-common` to `svm-utils`.
- Nuke it altogether and use Base16 (either with `format!()` or using [`hex`](https://github.com/KokaKiwi/rust-hex) or any other crate).

I think I would go for (3) given the chance but I'm quite neutral, @YaronWittenstein it's your choice.

**Comment by YaronWittenstein** [comment]
I prefer (3) as well. I agree that sometimes `utils` is a good, but right now it seems it's only about formatting
